### ISSUE TITLE
Incorrect installation instructions

### ISSUE THREAD

**Issue by smithara** [executablebooks/sphinx-comments#15]
At https://sphinx-comments.readthedocs.io/en/latest/#installation

I found that:
```
html_extensions = [
   "sphinx_comments"
]
```
had no effect, but instead needed:
```
extensions = [
   "sphinx_comments"
]
```

(I am actually not aware of how extensions work! or what `html_extensions` refers to)

Anyway thanks for the great tool!

**Comment by choldgraf** [comment]
thanks for reporting! fixed in https://github.com/executablebooks/sphinx-comments/pull/16 ✨
